### ISSUE TITLE
58E15B12.json has mistake in test output

### ISSUE THREAD

**Issue by volotat** [fchollet/ARC-AGI#86] opened 2021-08-16 16:14 UTC
![image](https://user-images.githubusercontent.com/14307880/129594523-65367d24-0110-4cf2-8192-34947c6b1b69.png)
It seems that by the rule when green and aqua lines are intersect they should produce magenta color. But in the provided test output single magenta cell is missing:
![image](https://user-images.githubusercontent.com/14307880/129595275-bc7e86a6-28d1-49c9-808e-1003026ccf72.png)

**Comment by neoneye** [comment] 2024-02-16 23:21
I can confirm this is still a problem.

![Screenshot 2024-02-17 at 00 13 06](https://github.com/fchollet/ARC/assets/147971/530fb02b-8c02-4dbe-a362-ab94fac84355)

**Comment by neoneye** [comment] 2024-05-22 13:21
This issue can now be closed. It was fixed in commit: https://github.com/fchollet/ARC/commit/84e7398ea44fe906ed1b704814f746b3c6388c17

[The task now looks like this in ARC-Interactive](https://neoneye.github.io/arc-staging/edit.html?dataset=ARC&task=58e15b12_v3)
![58e15b12_v3](https://github.com/fchollet/ARC/assets/147971/92ab0ff3-b8b3-4dfd-a64a-de0a0afdd9a0)

**Closed** 2024-06-16 22:06 UTC
